/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.integra.login.recovery.views;


import Clases.Utilidades;
import Control.msm;
import Formularios.Menu1;
import com.integra.login.recovery.ControladorRecuperacionPass;
import javax.swing.JLabel;
//import sicdabi_v1.Login;

/**
 *
 * @author cc11036
 */
public class PrincipalRecuperacionPass extends javax.swing.JDialog {

    private final PanelCambioContraseña pcc;
    private final PanelRecuperacionCorreo prc;
    private final PanelRecuperacionPregunta prp;
    private final ControladorRecuperacionPass crp;
    private String user="";
    private boolean typeRecovery = false;
    private boolean resetPassword = false;

    public PrincipalRecuperacionPass(Menu1 parent, boolean modal) {
        super(parent, modal);
        initComponents();
        user = parent.getCurrentUser();
        System.out.println("user->"+user);
        crp = new ControladorRecuperacionPass();
        pcc = new PanelCambioContraseña();
        prc = new PanelRecuperacionCorreo();
        prp = new PanelRecuperacionPregunta();
        pcc.setVisible(false);
        prc.setVisible(true);
        prp.setVisible(false);
        jPanel6.add(pcc);
        jPanel6.add(prc);
        JLabel t=prc.getjLabel5();
        t.setText(user);
        prc.setjLabel5(t);
        //parent.
        //prc.set
        //jPanel6.add(prp);
        //cargarPregunta();
        setLocationRelativeTo(null);
        this.setVisible(true);
        pack();
    }

    private void cargarPregunta() {
        //prp.getjLabel4().setText(crp.getSecurityQuestion(new ControladorAdministrarUsuario().getUserId(user)));
    }

    private void recuperacionPregunta() {
        try {
            String answer = prp.getjTextField2().getText();
            if (!answer.isEmpty()) {
                boolean res = crp.compareAnswer(answer);
                if (res) {
                    resetPass();
                }
            }
        } catch (Exception e) {
            System.out.println("recuperacionPregunta: " + e.getMessage());
        }
    }

    private void recuperacionCorreo() {
        try {
            if (!prc.isTypeToken()) {
                if (prc.isValidEmail()) {
                    if (crp.getUserEmail(user).equals(prc.getjTextField1().getText())) {
                        crp.recoveryFromEmail(user);
                    } else {
                        msm.ms_error("El correo ingresado no está asignado a su cuenta\nPor favor ingrese su correo");
                    }
                }
            } else {
                String token = prc.getjTextField1().getText();
                if (!token.isEmpty()) {
                    if (crp.compareTokenUserDB(token)) {
                        crp.resetPassEmail(user);
                        typeRecovery = true;
                        resetPass();
                    }
                }
            }
        } catch (Exception e) {
            System.out.println("recuperacionCorreo: " + e.getMessage());
        }
    }

    private void resetPass() {
        //jPanel5.setVisible(false);
        //prp.setVisible(false);
        
        
        
        
        
        prc.setVisible(false);
        pcc.setVisible(true);
        resetPassword = true;
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Recuperación de Contraseña");
        jPanel4.add(jLabel1);

        jPanel2.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/aceptar.png"))); // NOI18N
        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cancelar.png"))); // NOI18N
        jButton2.setText("Canelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);

        jPanel1.add(jPanel3, java.awt.BorderLayout.PAGE_END);

        jPanel6.setLayout(new java.awt.GridBagLayout());
        jPanel1.add(jPanel6, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 37, 35, 32);
        getContentPane().add(jPanel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (!resetPassword) {
            
                recuperacionCorreo();
            
        } else {
            try {
                if (pcc.isIsPassEquals()) {
                    crp.resetPasswordUser(new Utilidades().Encriptar(new String(pcc.getjPasswordField2().getPassword())), user);
                    this.dispose();
                    msm.ms_informacion("su contraseña ha sido reestablecida");
                } else {
                    msm.ms_alerta("Las contraseñas no coinciden");
                }
            } catch (Exception e) {
                System.out.println("error");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(PrincipalRecuperacionPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(PrincipalRecuperacionPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(PrincipalRecuperacionPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(PrincipalRecuperacionPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                PrincipalRecuperacionPass dialog = new PrincipalRecuperacionPass(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables

}
