/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Clases.Datos_Regisro_Producto;
import Clases.Utilidades;
import Control.msm;
import static clases.Validaciones.userExists;
import com.integra.login.ControladorLogin;
import com.integra.login.recovery.MD5;
import com.integra.login.recovery.views.PrincipalRecuperacionPass;
import com.integra.session.ModeloSession;
import com.integra.users.ControladorNuevoUsuario;
import com.sun.awt.AWTUtilities;

/**
 *
 * @author Amilcar Cortez
 */
public class Inicio_Sesion extends javax.swing.JDialog {
    Datos_Regisro_Producto Datos = new Datos_Regisro_Producto();
    int Id_Usuario_Baltazar;
    Menu1 menu;

    private ModeloSession mss;
    @SuppressWarnings("FieldMayBeFinal")
    private ControladorLogin clog;
    @SuppressWarnings("FieldMayBeFinal")
    private Menu1 parent;
    @SuppressWarnings("FieldMayBeFinal")
    private Utilidades utils;
    @SuppressWarnings("FieldMayBeFinal")
    private ControladorNuevoUsuario cnu;
    //private String currentUser;
    private String currentUser = "";

    public ModeloSession getMss() {
        return mss;
    }

    public Inicio_Sesion(Menu1 parent, boolean m) {
        super(parent, m);
        initComponents();
        AWTUtilities.setWindowOpaque(this, false);
        clog = new ControladorLogin();
        this.parent = parent;
        utils = new Utilidades();
        cnu = new ControladorNuevoUsuario();
        this.setLocationRelativeTo(null);
    }

//    private Inicio_Sesion() {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//    }

    public boolean verificarCamposVacios() {
        int sum = 0;
        sum += vacio(textFieldRoundImage24.getText());
        sum += vacio(passwordFieldRoundImage1.getText());
        return sum == 0;
    }

    private void limpiarCampos() {
        passwordFieldRoundImage1.setText("");
        textFieldRoundImage24.setText("");
    }

    public int vacio(Object o) {
        return (o.equals("") ? 1 : 0);
    }

    public String getCurrentUser() {
        return currentUser;
    }

    public void setCurrentUser(String currentUser) {
        this.currentUser = currentUser;
    }

    public boolean isLogged() {
        return mss.isLogged();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        passwordFieldRoundImage1 = new org.edisoncor.gui.passwordField.PasswordFieldRoundImage();
        textFieldRoundImage24 = new org.edisoncor.gui.textField.TextFieldRoundImage();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(passwordFieldRoundImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 140, 30));

        textFieldRoundImage24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldRoundImage24ActionPerformed(evt);
            }
        });
        getContentPane().add(textFieldRoundImage24, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 140, 30));

        jLabel27.setText("Contraseña");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, -1, -1));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/candado.png"))); // NOI18N
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        jLabel31.setForeground(new java.awt.Color(0, 0, 255));
        jLabel31.setText("¿Olvedaste tu contraseña?");
        jLabel31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel31MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, -1, 20));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/salir.png"))); // NOI18N
        jButton1.setText(" Salir   ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 380, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/aceptar.png"))); // NOI18N
        jButton2.setText("Aceptar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, -1, -1));

        jLabel30.setText("Usuario");
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/nuve de fondo.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel29.setText("Usuario");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, -1, -1));

        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 390, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldRoundImage24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldRoundImage24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldRoundImage24ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    @SuppressWarnings("static-access")
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            if (verificarCamposVacios()) {
                String user = textFieldRoundImage24.getText();
//                String pass = new String(textFieldRoundImage23.getPassword());
                @SuppressWarnings("RedundantStringConstructorCall")
                String pass = new String(passwordFieldRoundImage1.getText());
                userExists(cnu.isUserExists(user));
                ModeloSession mst = clog.doLogin(user, utils.Encriptar(pass));
                //ModeloSession mst = clog.doLogin(user, pass);
                //System.out.println(clog.getNivelAcceso(cnu.));
                if (clog.isUserActived(user)) {
                    this.parent.setMss(mst);
                    if (mst.isLogged()) {
                        dispose();
                        System.out.println("goood");
                        Datos.abrirConexion();
                        Id_Usuario_Baltazar=BuscarID("Select * from usuario where Nombre='"+user+"'", "usuario");
                        Datos.cerrarConexion();
                        System.out.println("ID_Baltazar "+Id_Usuario_Baltazar);
                        menu.Id_Usuario=Id_Usuario_Baltazar;
                    } else {
                        limpiarCampos();
                    }
                } else {
                    msm.ms_alerta("usuario desactivado");
                }
            } else {
                msm.ms_alerta("campos vacios");
            }
        } catch (Exception e) {
            msm.ms_error(e.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed
    public int BuscarID(String SQL, String Tabla) {
        int id = 0;
        try {
            Datos.Buscar(SQL, "" + Tabla);
            while (Datos.rs.next()) {
                id = Datos.rs.getInt(1);
            }
        } catch (Exception e) {
            System.out.print("Buscar ID Error al buscar en Tabla " + Tabla);
        }
        return id;
    }
    private void jLabel31MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel31MouseClicked
        if (vacio(textFieldRoundImage24.getText()) == 0) {
            if (!cnu.isUserExists(textFieldRoundImage24.getText())) {
                try {
                    parent.setCurrentUser(textFieldRoundImage24.getText());
                    this.setVisible(false);
                    PrincipalRecuperacionPass principalRecuperacionPass = new PrincipalRecuperacionPass(parent, true);
                    principalRecuperacionPass.setVisible(true);
                    dispose();
                    parent.setMss(new ModeloSession());
                } catch (Exception e) {
                    System.out.println(e.getMessage());
                }
            } else {
                msm.ms_error("El usuario no existe");
            }
        } else {
            msm.ms_alerta("Escriba su usuario");
        }

    }//GEN-LAST:event_jLabel31MouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Inicio_Sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Inicio_Sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Inicio_Sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Inicio_Sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Inicio_Sesion().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private org.edisoncor.gui.passwordField.PasswordFieldRoundImage passwordFieldRoundImage1;
    private org.edisoncor.gui.textField.TextFieldRoundImage textFieldRoundImage24;
    // End of variables declaration//GEN-END:variables
}
